version: 2.1
#dependecies
orbs:
  newman: postman/newman@0.0.2
  maven: circleci/maven@0.0.12
  sonarcloud: extendaretail/sonarcloud@1.0.0
#Jobs you want to run, each of them run in a different instance
jobs:
  newman-collection-run:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          #collection of postman you want to run
          collection: ./idea_postman.postman_collection.json
          #enviroment variables of the postman collection
          environment: ./dev.postman_environment.json
  build:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
      - run: mvn package
      - sonarcloud/scan_with_maven
#list of jobs you want to run in circle ci
workflows:
  main:
    jobs:
      - maven/test # checkout, build, test, and upload test results
      - build:
          context: sonarcloud
      - sonarcloud/check_quality_gate:
          context: sonarcloud
          requires:
            - build
      - newman-collection-run:
          filters:
            branches:
              only: master
