version: 2.1
#dependecies
orbs:
  newman: postman/newman@0.0.2
  maven: circleci/maven@0.0.12
  sonarcloud: sonarsource/sonarcloud@1.0.1
#Jobs you want to run, each of them run in a different instance
jobs:
  newman-collection-run:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          #collection of postman you want to run
          collection: ./idea_postman.postman_collection.json
          #enviroment variables of the postman collection
          environment: ./dev.postman_environment.json
  testJunit:
    steps:
      - checkout
      - maven/test # checkout, build, test, and upload test results
  build:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar
#list of jobs you want to run in circle ci
workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
      - testJunit
      - newman-collection-run:
          filters:
            branches:
              only: master
