jobs:
  commit:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
      - run: mvn package
      - sonarcloud/scan_with_maven
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1
version: 2.1
workflows:
  main:
    jobs:
      - commit:
          context: SonarCloud
      - sonarcloud/check_quality_gate:
          context: SonarCloud
          requires:
            - commit