version: 2.1
orbs:
  newman: postman/newman@0.0.2
jobs:
  newman-collection-run:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman-collection-run-env-timeout:
          collection: ./idea_postman.postman_collection.json
          environment: ./dev.postman_environment.json
          timeout: '5000'
  build:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
#      - run:
#          name: Analyze on SonarCloud
#          command: mvn verify sonar:sonar
workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
      - newman-collection-run:
          filters:
            branches:
              only: master
